import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "./_components/AppSidebar";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/*
            defaultOpen={false} → sidebar starts collapsed on every load.
            On mobile the shadcn SidebarProvider uses a Sheet (drawer),
            so collapsing by default keeps the full viewport free.
          */}
          <SidebarProvider defaultOpen={false}>
            <AppSidebar />

            {/* Wrapper so the trigger + page content stack vertically */}
            <div className="flex flex-col flex-1 min-w-0 overflow-hidden">
              {/* SidebarTrigger sits in its own bar so it never overlaps the Header */}
              <div className="flex items-center h-10 px-3 border-b bg-white shrink-0">
                <SidebarTrigger />
              </div>

              <Provider>
                {children}
              </Provider>
            </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
