import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "./_components/AppSidebar";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
       
          <SidebarProvider defaultOpen={true}>
            <AppSidebar />

            {/* Wrapper so the trigger + page content stack vertically */}
            <div className="flex flex-col flex-1 min-w-0 overflow-hidden">
           
              <Provider>
                {children}
              </Provider>
            </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
